### ISSUE TITLE
Binary compatibility issue in 1.15.0

### ISSUE THREAD

**Issue by larsrh** [typelevel/scalacheck#696]
Reported by @xuwei-k here: https://github.com/typelevel/scalacheck/commit/d4a3c257a5e696a6ae71b28923647e4cdba216c7#r43785860

### `org.scalacheck.Gen.someOf`

- 1.15.0 `<T:Ljava/lang/Object;>(Lorg/scalacheck/Gen<TT;>;Lorg/scalacheck/Gen<TT;>;Lscala/collection/immutable/Seq<Lorg/scalacheck/Gen<TT;>;>;)Lorg/scalacheck/Gen<Lscala/collection/Seq<TT;>;>;`

- 1.14.3 `<T:Ljava/lang/Object;>(Lorg/scalacheck/Gen<TT;>;Lorg/scalacheck/Gen<TT;>;Lscala/collection/immutable/Seq<Lorg/scalacheck/Gen<TT;>;>;)Lorg/scalacheck/Gen<Lscala/collection/immutable/Seq<TT;>;>;`

### `org.scalacheck.Gen.atLeastOne`

- 1.15.0 `<T:Ljava/lang/Object;>(Lorg/scalacheck/Gen<TT;>;Lorg/scalacheck/Gen<TT;>;Lscala/collection/immutable/Seq<Lorg/scalacheck/Gen<TT;>;>;)Lorg/scalacheck/Gen<Lscala/collection/Seq<TT;>;>;`

- 1.14.3 `<T:Ljava/lang/Object;>(Lorg/scalacheck/Gen<TT;>;Lorg/scalacheck/Gen<TT;>;Lscala/collection/immutable/Seq<Lorg/scalacheck/Gen<TT;>;>;)Lorg/scalacheck/Gen<Lscala/collection/immutable/Seq<TT;>;>;`

**Comment by larsrh** [comment]
These changes come from @non (#603), could you please comment?

**Comment by ashawley** [comment]
Oscar raised his concern in [a comment in #575](https://github.com/typelevel/scalacheck/pull/575/files#r329324663), the original PR, and pointed out that type erasure means it's still binary compatible.  So, this is only a source-compatibility breaking change?

**Comment by larsrh** [comment]
@johnynek Can you comment on this?

**Comment by johnynek** [comment]
1. I assume this project is running mima, if not it should. was that run? we should trust tools far more than humans in general to make these judgements.
2. to my eyes, it still appears the changed type is in the parameter of the result, and those are erased in JVM bytecode according to my understanding, so this appears binary (but not source) compatible to me. That said, maybe it is kind of bad kind of binary compatible because if you use the result it will result in a class cast exception... so maybe my argument is bad...

In 2.12 and earlier, I think immutable.Seq extends collection.Seq, but maybe that's not true in 2.13 so this differs a runtime exception...

If we are not running mima on all published versions, I think we need to update to do so, but even so, the version did bump to a new minor version, so maybe we just need to update the readme and say that there was a minor binary break in 2.13

**Comment by ashawley** [comment]
Mima is run on all versions, and even 2.13 after #482, but, yes, it only deals with binary compatible changes, IUUC.

**Comment by SethTisue** [comment]
At the moment I'm only glancing at this and not digging, but as per https://github.com/lightbend/mima/pull/299 shouldn't MiMa have warned on a signature change?

**Comment by ashawley** [comment]
You're right, Seth.  We disabled signature checking in 7bb0613.  That's probably the issue.

**Comment by ashawley** [comment]
Actually, that wasn't the issue.  Signature checking was enabled by default in 0.4.0, but then changed to opt-in in 0.7.0, see https://github.com/lightbend/mima/pull/471

**Comment by SethTisue** [comment]
@ashawley even if we set `mimaReportSignatureProblems` to true, won't the filter still filter the problem out?

**Comment by ashawley** [comment]
That's right.  Having both of these enabled didn't help.  Turning them off, we do get the signature problems reported by MiMa.

**Comment by ashawley** [comment]
We can probably remove the return type signatures added for `Gen.someOf` and `Gen.atLeastOne` in 126168f that would at least make things compatible again with what was in 1.14.3.  I believe this is because the types for `scala.collection.Seq` in 2.13 and later are different from 2.13 and earlier.  Inferred types by the compiler is the only way to get it right.  Otherwise, we'd probalby need to source-fork `Gen.scala`.

**Comment by johnynek** [comment]
You could just put those functions and type aliases in version dependent files and then call them from Gen.

**Comment by ashawley** [comment]
I predict Erik had an issue with lining up the types with `Gen.pick` which was that way because it had an explicit type signature of `Gen[collection.Seq]` that snuck in back during the 2.13 migration work. We're probably stuck with it.

**Comment by larsrh** [comment]
Are you running a release for this, @ashawley?

**Comment by ashawley** [comment]
No, I was not planning to do the 1.15.1 release.  Would appreciate if you'd be willing to do it again.  I'm not sure what others think, but it should be ready to go.

**Comment by larsrh** [comment]
OK, I will take care of it.

**Comment by larsrh** [comment]
I ran out of time today, but it's on my list for tomorrow.

**Comment by larsrh** [comment]
Done.
