### ISSUE TITLE
Migrate off of Travis CI

### ISSUE THREAD

**Issue by non** [typelevel/scalacheck#704]
It seems like Travis CI has majorly reduced their capacity for building open source projects. We should migrate somewhere else.

**Comment by ashawley** [comment]
I've added an initial shell of a build in GitHub actions in 2163aa4, just so we have a working CI.  

I need to audit it further, but it looks like it builds the primary stuff.  Still need to see how to do these:

- Scala native builds
- Build example projects
- Running benchmark smoke test

**Comment by ashawley** [comment]
For now, maybe we should shut off pull request builds on Travis to avoid queuing builds?  It's good to have when merges to master happen since it's the full build.  I'd do it myself, but I don't have the privs to do it for some reason. Maybe someone else does?  https://travis-ci.org/github/typelevel/scalacheck/settings

![Screen Shot 2020-11-03 at 10 40 19 PM](https://user-images.githubusercontent.com/358615/98066649-9f4a4500-1e25-11eb-986e-d600c31820f7.png)

**Comment by SethTisue** [comment]
fwiw, the repos I moved from travis-ci.org to travis-ci.com recently have all been doing just fine the last few days (jobs run promptly), so at least as a short term measure, someone with admin access in the typelevel org (it's apparently not enough to have admin access just in this repo) could flip the switch to move to travis-ci.com

**Comment by ashawley** [comment]
Ok, good to know.  That would be good, because we don't have concurrency either, so it's a slow parade.

**Comment by ashawley** [comment]
Oh, geez.  Daniel has made a bunch of headway with GitHub Actions in #705.

**Comment by larsrh** [comment]
I just disabled the Travis CI build, so we can technically close this. FWIW, I prefer Daniel's approach with managed workflow configuration.

**Comment by ashawley** [comment]
Ok.  Hopefully, we can better coordinate work here in the future so we avoid duplication.

**Comment by ashawley** [comment]
I was interested in having both CI still working to some degree to sanity check the new setup, but if we're confident that it's fine, then we can shut off Travis.

I guess the only other concern is getting 1.15.1 out, since there are some significant defects that need to go out pretty soon.
