### ISSUE TITLE
conditional property doc example

### ISSUE THREAD

**Issue by mgk** [typelevel/scalacheck#74]
After going through the very nice ScalaCheck tutorial and using ScalaCheck successfully for a Coursera homework assignment I am puzzled about the conditional property example in the tutorial. The example works:

```
val propMakeList = forAll { n: Int =>
  (n >= 0 && n < 10000) ==> (List.make(n, "").length == n)
}
```

What I thought was a similar example does not work:

```
val rangeLengthSmallIntCP = forAll { x: Int =>
  (x > 0 && x < 1000) ==> ((1 to x).size == x)
}
rangeLengthSmallCP.check
! Gave up after only 15 passed tests. 86 tests were discarded.
```

Now I understand that random sampling of the 1e9 Int space is has a very small chance of choosing in the the range (1 to 1000), but I would think that would cause the tutorial example to also give up. My example fails (gives up) even if I adjust the bounds to 1e4 or 1e5.

I understand I can write:

```
val rangeLengthSmallIntGen = forAll(Gen.choose(1, 1000)) { x: Int =>
  (1 to x).size == x
}
```

and that's a perfectly clear expression of the intent.

[1] Why does my example fail when the tutorial example works?

[2] Is the `forAll(Gen.choose())` example perhaps a better best practice example to use in the tutorial for limiting tests to small ints?

Thanks for your time and for creating a really nifty package.

**Comment by Philippus** [comment]
1. I think it's because of the  `n >= 0` part in propMakeList.
ScalaCheck has a bias for special values (like 0 and 1).
Probably in this case the values 0 and 1 are selected enough times for 100 successful tests.

If you change your `x > 0` to `x >=0` you will also get 100 successful tests (but mainly 0 and 1 will be tested).

You can play around with `collect` to see the distribution of the generated data:

```scala
  val propMakeList = forAll { n: Int =>
    collect(n) {
      (n >= 0 && n < 10000) ==> (List.fill(n)("").length == n)
    }
  }
```

(This also means that the example given in the documentation is a little unfortunate as the property is only really tested for values 0 and 1.)

2. yes, I think so.

**Comment by ashawley** [comment]
That's correct.  The example uses fencing so it is a fragile test.  The tutorial now includes information about discarded generated values.
