### ISSUE TITLE
Predictable repetition in generated values

### ISSUE THREAD

**Issue by leviramsey** [typelevel/scalacheck#840]
See scalatest/scalatest#2054

```scala
trait Arithmetic {
  def add(x: Int, y: Int): Int
}

object ArithmeticProps {
  val arithmetic: Arithmetic = _ + _

  val dependsOnInput =
    Prop.forAll { (x: Int, y: Int, z: Int) =>
      println(s"$x $y $z")

      val addXY = arithmetic.add(x, y)
      val addXZ = arithmetic.add(x, z)

      (addXY == addXZ) == (y == z)
    }
}
```

`ArithmeticProps.dependsOnInput.check()` results in output like

```
0 1 -467377710
1 -467377710 -533146462
-467377710 -533146462 1
-533146462 1 1258003880
1 1258003880 1
1258003880 1 -830507445
1 -830507445 -1595422142
```

Note that the `x` value for a given run is the previous `y` and the `y` value for a given run is the previous `z`.

**Comment by leviramsey** [comment]
This behavior was not observed in 1.14.3 (by way of the scalatest integration).

**Comment by leviramsey** [comment]
This looks to be downstream of the seed handling change in #651 and will probably(?) only affect generating values where the generator only needs one random number (so `Int`/`Char`/etc.).

Varying the number of `reseed`s in `Test.check` (maybe `1 + (n + d) % 7` times?) should make this a little more coincidental.

**Comment by ashawley** [comment]
ScalaCheck uses its own deterministic RNG.  It's meant for repeatability, but also tries to generate values quickly.  I predict what you're seeing in your example is an implementation detail of how the support for arity in`Prop.forAll` is done.  The multiple argument `Prop.forAll` is composed with calls to the `Prop.forAll` of one argument.  The one argument `Prop.forAll` calls `slideSeed` once, thus each parameter shares the same initial seed, but is only separated by one slide of the seed.  This explains why the same value is reproduced between arguments to `Prop.forAll`.

If I understand your addition example, this could seem wasteful since addition is commutative.  However, not all tests have that property.  I suppose the predictable repetition is odd compared to true RNG.  Even with parameter repetition, the tuples themselves are unique.

It looks like the case reported downstream with ScalaTest is related to generating two lists, but they're not distinct?

**Comment by ashawley** [comment]
Yes, the repeating values, in this case with parameters across runs, is probably just an aesthetic issue.  The test cases under discussion so far are ones that would expose the deterministic RNG and also how it is ScalaCheck is passing around the next seed in its internals in a, albeit, simplistic way.

Your proposal of randomly spinning the RNG several more times is the simplest and it's good for that reason.  Unfortunately, it is at a hotspot in the library.  I'm not sure we could do that without some further analysis, but also without a better justification or principle for doing so.  Typically, domain coverage or the inability to reasonably compose generators would be good cases for making the change.  Fortunately, the reused RNG values across parameters hasn't been a material issue to my knowledge.

**Comment by leviramsey** [comment]
I've tweaked the proposed change to make it configurable with a default of no-change with minimal performance impact.  Users/frameworks which care about this can opt-in.
