### ISSUE TITLE
Drop Scala 3.0, publish for 3.1?

### ISSUE THREAD

**Issue by armanbilge** [typelevel/scalacheck#878]
Unblocks:
- https://github.com/typelevel/scalacheck/pull/868

See also discussion in:
- https://github.com/scalameta/munit/pull/477#issuecomment-1068501049
- https://github.com/typelevel/scalacheck/pull/868#issuecomment-1067995736
- https://github.com/typelevel/cats/issues/4143#issuecomment-1061127957
- https://github.com/typelevel/scalacheck/pull/875#issuecomment-1060178735

scalacheck is definitely in more of a maintenance-mode so anyone who _truly_ wants to stick fast to 3.0 can pin to Scalacheck 1.15.4 without missing out on much. We can merge outstanding PRs and do a last hurrah 1.15.5 on 3.0 before bumping.

**Comment by rossabaker** [comment]
I spent my formative years in the enterprise salt mines, and I vigorously maintain the idea that libraries should drop support _when pinning hurts_, not _because it's there_.  We now have a concrete reason that pinning hurts, and I have not heard any specific 3.0 -> 3.1 tales of woe.  "It's time", says the archconservative.  

But let's not delude ourselves: when this hits Maven Central, some maintainers are going to bump because It's there, and that's going to be the end of 3.0 for a wide swath of the ecosystem, for a test-only dependency.  No great loss, but until we have the scala-release flag, I'm digging a new trench at 3.1.

**Comment by armanbilge** [comment]
> some maintainers are going to bump because It's there

Eh, that same group probably is already on 3.1.1 because it's there. Note that bumping to Scala 3.1 is easy (merge the Steward PR and carry on), but a bumping Scalacheck PR will break a project still on 3.0 until they manually bump to Scala 3.1.

**Comment by SethTisue** [comment]
> let's not delude ourselves: when this hits Maven Central, some maintainers are going to bump because It's there, and that's going to be the end of 3.0 for a wide swath of the ecosystem, for a test-only dependency. No great loss, but until we have the scala-release flag, I'm digging a new trench at 3.1

@sjrd @julienrf @smarter @romanowski is there sentiment at the Scala Center or on the Scala 3 team that merging #879 would be a Very Bad Thing?

personally I'm in the "let's just pretend 3.0 never existed" camp

**Comment by julienrf** [comment]
I generally lean towards staying on 3.0, but in the case of scalacheck the situation is different:

> scalacheck is definitely in more of a maintenance-mode so anyone who _truly_ wants to stick fast to 3.0 can pin to Scalacheck 1.15.4 without missing out on much.

:100: 

So, I don’t think merging #879 would be a Very Bad Thing.

**Comment by smarter** [comment]
I'd even say it's a Good Thing but we've had this discussion already: https://github.com/typelevel/cats/pull/4016#issuecomment-946418651
