### ISSUE TITLE
Release 1.17.0?

### ISSUE THREAD

**Issue by SethTisue** [typelevel/scalacheck#912]
1.6.0 was in April, so a fair amount of time has passed, and a number of PRs have been merged, most notably:

* Fix the cross-platform time arbitraries, again by @armanbilge in https://github.com/typelevel/scalacheck/pull/889
* [Commands] Fix MatchError when using multiple workers by @yannkaiser-asana in https://github.com/typelevel/scalacheck/pull/894
* Keep the same error type while shrinking by @AurelienRichez in https://github.com/typelevel/scalacheck/pull/838
* fix wrong match in shrinker (fixes #909) by @AurelienRichez in https://github.com/typelevel/scalacheck/pull/910
* Deterministically vary the number of seed slides in Test.check by @leviramsey in https://github.com/typelevel/scalacheck/pull/911

maybe it's time to pull release levers...?

most of the above are bugfixes, but #911 adds API, so I guess the version number would be 1.17.0?

**Comment by armanbilge** [comment]
👍 indeed the base version in the build was already bumped to 1.17.
https://github.com/typelevel/scalacheck/blob/7bb1a47af2313f7e7935d34cce255f7b7c0b1b31/build.sbt#L55

Ross has been promising a release since https://github.com/typelevel/scalacheck/pull/894#pullrequestreview-995945167 but got a bit busy I suspect :)

I don't have the power but if @SethTisue does pulling the crank is easy here.
https://typelevel.org/sbt-typelevel/faq.html#how-do-i-cut-a-release

**Comment by SethTisue** [comment]
Volunteer to cut a release? I consider myself a maintainer-of-last-resort in this repo.

**Comment by armanbilge** [comment]
It's really not that hard :) create release, auto-generate notes (or copy-paste your nice ones above) and boom publish :)

**Comment by SethTisue** [comment]
OKAY FINE :-P

* https://github.com/typelevel/scalacheck/releases/tag/v1.17.0
* https://github.com/typelevel/scalacheck/actions/runs/3064360695/jobs/4947418425
* https://repo1.maven.org/maven2/org/scalacheck/scalacheck_3/1.17.0/
